version: '3.8'

services:
  lorem-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - PORT=4000
    env_file:
      - .env
    command: npm start
    restart: unless-stopped
    networks:
      - lorem-network

networks:
  lorem-network:
    driver: bridge
