services:
  anything-ipsum:
    image: ghcr.io/damienmarill/anything-ipsum:latest
    pull_policy: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      # Mistral AI Configuration
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-your_mistral_api_key_here}
      # Application Configuration
      - APP_URL=${APP_URL:-http://localhost:4000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
