name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        target: production
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Version ${{ github.ref_name }}

          ### 📦 Docker Image
          ```bash
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ```

          ### 💻 Quick Start
          ```bash
          # Using docker-compose
          git clone https://github.com/${{ github.repository }}.git
          cd anything-ipsum
          MISTRAL_API_KEY=your_key docker-compose up

          # Using docker run
          docker run -p 4000:4000 \
            -e MISTRAL_API_KEY=your_key \
            -e APP_URL=http://localhost:4000 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ```

          ### 🔗 Links
          - 🌐 **Application**: http://localhost:4000
          - 📋 **Health Check**: http://localhost:4000/api/health
          - 🐳 **Docker Hub**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          ### ⚙️ Environment Variables
          - `MISTRAL_API_KEY`: Your Mistral AI API key
          - `APP_URL`: Application URL (default: http://localhost:4000)
          - `NODE_ENV`: Environment mode (default: production)

          ---

          ### Changes
          - Auto-generated release from tag push
        draft: false
        prerelease: false
